name: master
on:
  push:
    tags:
      - *

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      - name: "setup nodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: npm

      - name: "install dependencies"
        run: npm install

      - name: "build app production"
        run: npm run build

      - name: "install dependencies"
        run: apt install -y rsync openssh-client

      - name: "setup ssh"
        run: |
          mkdir -p ~/.ssh
          echo ${{secrets.SSH_PRIVATE_KEY}} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{vars.SSH_HOST}} > ~/.ssh/known_hosts

      - name: "deploy on server distant"
        run: rsync -avz --delete ./dist "${{vars.SSH_USERNAME}}@${{vars.SSH_HOST}}:/var/www/html"
