name: master
on:
  push:
    branches:
      - main

jobs:
  build-lint-test:
    uses: ./.github/worklows/build-lint-test.yaml

  release:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "display new release"
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
